trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: OpsGuildAutomationRepo
      type: git
      name: Engineering/OpsGuild.Automation
      ref: refs/heads/main
    - repository: OpsGuildPipelineTools
      type: git
      name: Engineering/opsguild.pipeline-tools
      ref: refs/heads/main
    - repository: templates
      type: github
      name: osisoft/OSI-Samples
      endpoint: osisoft/OSI-Samples

variables:
  - template: '/miscellaneous/build_templates/variables.yml@templates'
  - name: analysisProject
    value: sample-adh-pi_to_adh_transfer_verification-powershell

jobs:
  - job: Tests
    strategy:
      matrix:
        windows:
          agentOS: Windows_NT
    pool:
      name: 00-OSIManaged-Containers
      demands: Agent.OS -equals $(agentOS)
    variables:
      - name: StartIndex
        value: "2022-03-12T00:00:00Z"
      - name: EndIndex
        value: "2022-03-15T00:00:00Z"
      - name: StreamId
        value: 'PI_$(DataArchiveName)_1'
    steps:
      - checkout: self
      - checkout: OpsGuildPipelineTools
      
      - task: DownloadPackage@1
        inputs:
          packageType: 'nuget'
          feed: 'Main'
          definition: 'OSIsoft.PowerShell.MSIL.MSI' # Can also be package name
          version: '2.2.2.255'
          extract: true
          downloadPath: '$(Pipeline.Workspace)'
      
      - powershell: |
        cd $(Pipeline.Workspace)
        ls
      
      - powershell: | 
        cd OSIsoft.PowerShell.MSIL.MSI
        ls
      
      - powershell: $(Pipeline.Workspace)/OSIsoft.PowerShell.MSIL.MSI

      - template: '/miscellaneous/build_templates/appsettings.yml@templates'
        parameters:
          secrets: 'TenantId, NamespaceId, ClientId, ClientSecret, DataArchiveName, Username, Password'
      
      - template: '/Templates/Utilities/InstallAFSDK.step.v0.yml@OpsGuildPipelineTools'
      
      - powershell: |
          Import-Module -Name 'C:\Program Files (x86)\PIPC\OSIsoft.PowerShell' -Verbose
          Get-Command -Module OSIsoft.PowerShell
        displayName: 'Setup environment'

      - task: PowerShell@2
        inputs:
          targetType: 'filePath'
          filePath: $(System.DefaultWorkingDirectory)\sample-adh-pi_to_adh_transfer_verification-powershell\Test.ps1
          workingDirectory: $(System.DefaultWorkingDirectory)\sample-adh-pi_to_adh_transfer_verification-powershell
        displayName: 'Run tests'
        
  - job: Code_Analysis
    pool:
      name: 00-OSIManaged-Containers
      demands: Agent.OS -equals Windows_NT
    steps:
      - powershell: Install-Module -Name PSScriptAnalyzer -Force
        displayName: Install code analyzer
        
      - powershell: Invoke-ScriptAnalyzer -EnableExit -Path GetData.ps1
        failOnStderr: true
        displayName: Run analysis

  - template: '/miscellaneous/build_templates/code-analysis.yml@templates'
    parameters:
      buildSteps:
        - checkout: self
        - checkout: OpsGuildPipelineTools

        - template: '/Templates/Utilities/InstallAFSDK.step.v0.yml@OpsGuildPipelineTools'
      skipPolaris: true
