trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: ArchitectureRepo
      type: git
      name: Architecture/Architecture
      ref: refs/heads/main
    - repository: OpsGuildPipelineTools
      type: git
      name: DevOps/opsguild.pipeline-tools
      ref: refs/heads/main
    - repository: templates
      type: github
      name: AVEVA/AVEVA-Samples
      endpoint: AVEVA

variables:
  - name: analysisProject
    value: sample-adh-pi_to_adh_transfer_verification-powershell

parameters:
  - name: pool
    default: DevOps-Managed-Ubt22-Mdp
  - name: containerDemands
    type: object
    default: ['Agent.OS -equals Windows_NT']

jobs:
  - job: Tests
    condition: ne(variables['Build.Reason'], 'Schedule')
    pool:
      name: ${{ parameters.pool }}
      demands: ${{ parameters.containerDemands }}
    variables:
      - name: PointIds
        value: 2
    steps:
      - checkout: self
      - checkout: OpsGuildPipelineTools
      
      - task: DownloadPackage@1
        inputs:
          packageType: 'nuget'
          feed: 'Main'
          definition: 'OSIsoft.PowerShell.MSIL.MSI' # Can also be package name
          version: '2.2.2.255'
          extract: true
          downloadPath: '$(Pipeline.Workspace)'
        displayName: 'Get PI Powershell'
      
      - powershell: $(Pipeline.Workspace)/Content/MSI/PIPowerShell/PIPowerShell_x86.msi
        displayName: 'Install PI Powershell'

      - template: '/miscellaneous/build_templates/appsettings.yml@templates'
        parameters:
          secrets: 'TenantId, NamespaceId, Resource, ClientId, ClientSecret, DataArchiveName, Username, Password'
      
      - template: '/Templates/Utilities/InstallAFSDK.step.v0.yml@OpsGuildPipelineTools'
      
      - powershell: |
          Import-Module -Name 'C:\Program Files (x86)\PIPC\OSIsoft.PowerShell' -Verbose
          Get-Command -Module OSIsoft.PowerShell
        displayName: 'Setup environment'

      - task: PowerShell@2
        inputs:
          targetType: 'filePath'
          filePath: $(System.DefaultWorkingDirectory)\sample-adh-pi_to_adh_transfer_verification-powershell\Test.ps1
          workingDirectory: $(System.DefaultWorkingDirectory)\sample-adh-pi_to_adh_transfer_verification-powershell
        displayName: 'Run tests'
        
  - job: Code_Analysis
    pool:
      name: ${{ parameters.pool }}
      demands: ${{ parameters.containerDemands }}
    steps:
      - powershell: Install-Module -Name PSScriptAnalyzer -Force
        displayName: Install code analyzer
        
      - powershell: Invoke-ScriptAnalyzer -EnableExit -ExcludeRule PSAvoidUsingConvertToSecureStringWithPlainText -Path GetData.ps1
        failOnStderr: true
        displayName: Run analysis

  - template: '/miscellaneous/build_templates/code-analysis.yml@templates'
    parameters:
      buildSteps:
        - checkout: self
        - checkout: OpsGuildPipelineTools

        - template: '/Templates/Utilities/InstallAFSDK.step.v0.yml@OpsGuildPipelineTools'
      skipPolaris: true
